# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
           in_memory:
               memory:
                   users:
                       user1:
                           password: u1
                           roles: 'ROLE_USER'
                       admin1:
                           password: a1
                           roles: 'ROLE_ADMIN'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check
            logout:
               path: /quit
               target: /

    access_control:
            - { path: ^/adminpage, roles: ROLE_ADMIN }
            - { path: ^/userpage, roles: [ROLE_ADMIN,ROLE_USER] }
